# Site settings
title: ViennaKaggle
email: office@chaosmail.at
description: "ViennaKaggle Blog"
baseurl: ""
url: "https://viennakaggle.github.io"

author:
  fullname: ViennaKaggle
  meetup: Vienna-Kaggle-Meetup-Machine-Learning-Competitions
  github: ViennaKaggle
  twitter: "#ViennaKaggle"
  disqus: chaosmail

google_analytics: 'UA-69537743-1'

# Build settings
markdown: kramdown
